# Generated by Django 4.0.8 on 2023-04-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_aceite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aceite',
            old_name='table',
            new_name='tabela',
        ),
    ]
