# Generated by Django 4.0.8 on 2023-05-05 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0016_remove_tabela_notis_sender_and_more'),
        ('instituicao', '0009_tabela_notis_aceitar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceitar',
            name='notificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noti.notificacao'),
        ),
    ]
