# Generated by Django 4.0.8 on 2023-05-05 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0010_alter_aceitar_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceitar',
            name='notificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicao.tabela_notis'),
        ),
    ]
