# Generated by Django 4.0.8 on 2023-07-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0012_remove_tabela_notis_notificacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabela',
        ),
    ]
