# Generated by Django 4.0.8 on 2023-01-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='idade',
        ),
    ]
