# Generated by Django 4.0.8 on 2023-01-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
