# Generated by Django 4.0.8 on 2023-01-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0001_initial'),
        ('accounts', '0005_profile_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='responsavel',
            field=models.ManyToManyField(to='responsavel.responsavel'),
        ),
    ]
