# Generated by Django 4.0.8 on 2023-01-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0001_initial'),
        ('accounts', '0006_profile_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='profile',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responsavel.responsavel'),
        ),
    ]
