# Generated by Django 4.0.8 on 2023-01-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_peoplelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplelist',
            name='people',
        ),
        migrations.RemoveField(
            model_name='peoplelist',
            name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='responsavel',
        ),
    ]
