# Generated by Django 4.0.8 on 2023-01-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_bairro_alter_profile_cidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('use', 'use'), ('atual', 'atual'), ('exc', 'exc'))},
        ),
    ]
