# Generated by Django 4.0.8 on 2023-02-04 02:05

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAdm', models.CharField(default='Dorcas(nome padrão)', max_length=100, null=True)),
                ('nomeInst', models.CharField(default='Dorcas(nome padrão)', max_length=100, null=True)),
                ('telefonedoAdm', models.CharField(default='Telefone do Adiministrador', max_length=20, null=True)),
                ('telefonedoInst', models.CharField(default='Telefone de contato do instituição', max_length=20, null=True)),
                ('funcaoAdm', models.CharField(default='Função do Administrador na instituição', max_length=100, null=True)),
                ('dtaDeFuncaoAdm', models.DateTimeField(default='Data de inicio de função do Administrador', null=True)),
                ('dtaDenascAdm', models.DateTimeField(default='Data de nascimento do Adiministrador', null=True)),
                ('emailAdm', models.EmailField(default='Email do Adiministrador', max_length=254, null=True)),
                ('emailInst', models.EmailField(default='Email do Instituiçao', max_length=254, null=True)),
                ('cidadeAdm', models.CharField(default='Cidade do Adiministrador', max_length=150, null=True)),
                ('estadoAdm', models.CharField(default='Estado do Adiministrador', max_length=150, null=True)),
                ('ruaAdm', models.CharField(default='Rua do Adiministrador', max_length=150, null=True)),
                ('numeroAdm', models.CharField(default='Número da casa do Adiministrador', max_length=10, null=True)),
                ('bairroAdm', models.CharField(default='Bairro do Adiministrador', max_length=150, null=True)),
                ('cpfAdm', models.IntegerField(default='Cpf do Adiministrador', max_length=150, null=True)),
                ('cidadeInst', models.CharField(default='Cidade da Instituição', max_length=150, null=True)),
                ('estadoInst', models.CharField(default='Estado da Instituição', max_length=150, null=True)),
                ('ruaInst', models.CharField(default='Rua da Instituição', max_length=150, null=True)),
                ('eixoInst', models.CharField(default='Eixo da Instituição', max_length=150, null=True)),
                ('categoriaInst', models.CharField(default='Categoria da Instituição', max_length=150, null=True)),
                ('numeroInst', models.CharField(default='Número da cede da Instituição', max_length=10, null=True)),
                ('bairroInst', models.CharField(default='Bairro da Instituição', max_length=150, null=True)),
                ('cnpj', models.IntegerField(default='Cnpj da Instituição', null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path_profile, verbose_name='Picture')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path_banner, verbose_name='Banner')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('use', 'use'), ('atual', 'atual'), ('exc', 'exc')),
            },
        ),
    ]
