# Generated by Django 4.0.8 on 2023-02-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='cpfAdm',
            field=models.IntegerField(default='Cpf do Adiministrador', null=True),
        ),
    ]
