# Generated by Django 4.0.8 on 2023-02-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_instituicao_cpfadm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'permissions': (('inst', 'inst'), ('atual', 'atual'), ('exc', 'exc'))},
        ),
    ]
