# Generated by Django 4.0.8 on 2023-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_instituicao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='dtaDeFuncaoAdm',
            field=models.DateField(default='Data de inicio de função do Administrador', null=True),
        ),
    ]
