# Generated by Django 4.0.8 on 2023-02-05 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_instituicao_dtadefuncaoadm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='dtaDenascAdm',
        ),
    ]
