# Generated by Django 4.0.8 on 2023-02-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_instituicao_dtadenascadm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='cpfAdm',
            field=models.IntegerField(null=True),
        ),
    ]
