# Generated by Django 4.0.8 on 2023-02-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_instituicao_cpfadm'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='dtaDeFuncaoAdm',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='dtaDenascAdm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cnpj',
            field=models.IntegerField(null=True),
        ),
    ]
