# Generated by Django 4.0.8 on 2023-02-19 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_instituicao_dtadefuncaoadm_instituicao_dtadenascadm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='user',
            new_name='autor',
        ),
    ]
