# Generated by Django 4.0.8 on 2023-02-20 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_rename_user_instituicao_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='autor',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Dorcas(nome padrão)', max_length=100, null=True)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('cidade', models.CharField(max_length=150, null=True)),
                ('estado', models.CharField(max_length=150, null=True)),
                ('rua', models.CharField(max_length=150, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('bairro', models.CharField(max_length=150, null=True)),
                ('cpf', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
