# Generated by Django 4.0.8 on 2023-02-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_usuario_user_delete_perfil_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='bairroAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='cidadeAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='cpfAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='dtaDeFuncaoAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='dtaDenascAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='emailAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='emailInst',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='estadoAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='funcaoAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='nomeAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='nomeInst',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='numeroAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='ruaAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='telefonedoAdm',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='telefonedoInst',
        ),
    ]
