# Generated by Django 4.0.8 on 2023-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_profile_dtadenascadm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='idade',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dtaDeFuncaoAdm',
            field=models.IntegerField(max_length=254, null=True),
        ),
    ]
