# Generated by Django 4.0.8 on 2023-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_profile_idade_alter_profile_dtadefuncaoadm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dtaDeFuncaoAdm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dtaDenascAdm',
            field=models.IntegerField(null=True),
        ),
    ]
