# Generated by Django 4.0.8 on 2023-02-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_profile_dtadefuncaoadm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'permissions': (('inst', 'inst'), ('atual', 'atual'), ('exclude', 'exclude'))},
        ),
    ]
