# Generated by Django 4.0.8 on 2023-02-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_instituicao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'permissions': (('inst', 'inst'), ('atualizar', 'atualizar'), ('exclude', 'exclude'))},
        ),
    ]
