# Generated by Django 4.0.8 on 2023-02-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_instituicao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.IntegerField(default='000000000', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dtaDeFuncaoAdm',
            field=models.IntegerField(default='00/00/0000', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dtaDenascAdm',
            field=models.CharField(default='00/00/0000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emailAdm',
            field=models.EmailField(default='email@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='formacao',
            field=models.CharField(default='ex.: Letras', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='funcaoAdm',
            field=models.CharField(default='ex.: Leitor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='habilidades',
            field=models.CharField(default='ex.: Contar histórias', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nome',
            field=models.CharField(default='Dorcas(nome padrão)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(default='ex.: Feminino', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(default='55 DDD 000000000', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trabalho',
            field=models.CharField(default='ex.: Professora', max_length=150, null=True),
        ),
    ]
