# Generated by Django 4.0.8 on 2023-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_profile_cpf_alter_profile_dtadefuncaoadm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dtaDeFuncaoAdm',
            field=models.CharField(default='00/00/0000', max_length=100, null=True),
        ),
    ]
