# Generated by Django 4.0.8 on 2023-02-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_profile_dtadenascadm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.IntegerField(blank=True, default='000000000', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dtaDeFuncaoAdm',
            field=models.CharField(blank=True, default='00/00/0000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emailAdm',
            field=models.EmailField(blank=True, default='email@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='formacao',
            field=models.CharField(blank=True, default='ex.: Letras', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='funcaoAdm',
            field=models.CharField(blank=True, default='ex.: Leitor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='habilidades',
            field=models.CharField(blank=True, default='ex.: Contar histórias', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(blank=True, default='ex.: Feminino', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, default='55 DDD 000000000', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trabalho',
            field=models.CharField(blank=True, default='ex.: Professora', max_length=150, null=True),
        ),
    ]
