# Generated by Django 4.0.8 on 2023-02-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_profile_cpf_alter_profile_dtadefuncaoadm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='bairroInst',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='cidadeInst',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='estadoInst',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='numeroInst',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='ruaInst',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='bairro',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='cidade',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='email',
            field=models.EmailField(blank=True, default='email@gmail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='estado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(default='Dorcas(nome padrão)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='rua',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(blank=True, default='55 DDD 000000000', max_length=25, null=True),
        ),
    ]
