# Generated by Django 4.0.8 on 2023-02-21 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0038_remove_instituicao_bairroinst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('sexo', models.CharField(choices=[['F', 'Feminino'], ['M', 'Masculino'], ['N', 'Nenhuma das opções']], max_length=1, null=True)),
                ('curso', models.CharField(choices=[['Info', 'Informática'], ['Agro_ind', 'Agroindrustria'], ['Agro', 'Agropecuaria'], ['N', 'nenhuma'], ['Super', 'superior']], max_length=10, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('add', 'add'), ('perfil', 'perfil')),
            },
        ),
    ]
