# Generated by Django 4.0.8 on 2023-02-21 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0040_remove_instituicao_user_instituicao_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
