# Generated by Django 4.0.8 on 2023-02-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_instituicao_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
