# Generated by Django 4.0.8 on 2023-02-21 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_delete_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='author',
        ),
    ]
