# Generated by Django 4.0.8 on 2023-02-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_remove_instituicao_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='bio',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
