# Generated by Django 4.0.8 on 2023-02-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_instituicao_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='bio',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
