# Generated by Django 4.0.8 on 2023-02-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_instituicao_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Dorcas(nome padrão)', max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
