# Generated by Django 4.0.8 on 2023-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_instituicao_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dtaDenascAdm',
        ),
    ]
