# Generated by Django 4.0.8 on 2023-03-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_m_remove_profile_dtadenascadm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
