# Generated by Django 4.0.8 on 2023-04-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_delete_m_profile_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'permissions': (('inst', 'inst'), ('atualizar', 'atualizar'), ('exclude', 'exclude'), ('foto', 'foto'))},
        ),
    ]
