# Generated by Django 4.0.8 on 2023-04-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_instituicao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('use', 'use'), ('atual', 'atual'), ('exc', 'exc'), ('foto', 'foto'))},
        ),
    ]
