# Generated by Django 4.0.8 on 2023-04-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='responsavel',
            field=models.BooleanField(default=False),
        ),
    ]
