# Generated by Django 4.0.8 on 2023-04-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_profile_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='responsavel',
        ),
    ]
