# Generated by Django 4.0.8 on 2023-04-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_rename_responsavel_r_profile_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='caption',
            field=models.ManyToManyField(related_name='contents', to='accounts.r'),
        ),
    ]
