# Generated by Django 4.0.8 on 2023-04-16 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0056_profile_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='responsavel',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='R',
        ),
    ]
