# Generated by Django 4.0.8 on 2023-04-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='user',
            new_name='autor',
        ),
    ]
