# Generated by Django 4.0.8 on 2023-04-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_rename_autor_instituicao_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='eixoInst',
            field=models.CharField(choices=[('animais', 'animais'), ('criancas', 'criancas'), ('idosos', 'idosos'), ('religiosa', 'religiosa'), ('outra', 'outra')], max_length=15, null=True),
        ),
    ]
