# Generated by Django 4.0.8 on 2023-04-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_instituicao_eixoinst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='categoriaInst',
        ),
    ]
