# Generated by Django 4.0.8 on 2023-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_remove_instituicao_categoriainst'),
    ]

    operations = [
        migrations.CreateModel(
            name='idade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
