# Generated by Django 4.0.8 on 2023-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='eixoInst',
            new_name='eixoAtuacao',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='dataNascimento',
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
