# Generated by Django 4.0.8 on 2023-05-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_rename_eixoinst_instituicao_eixoatuacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='idade',
        ),
    ]
