# Generated by Django 4.0.8 on 2023-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_alter_instituicao_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
