# Generated by Django 4.0.8 on 2023-05-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_alter_instituicao_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='bio',
        ),
    ]
