# Generated by Django 4.0.8 on 2023-05-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_remove_instituicao_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
