# Generated by Django 4.0.8 on 2023-05-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_usuarioscomcamposadicionais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuariosComCamposAdicionais',
        ),
    ]
