# Generated by Django 4.0.8 on 2023-05-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_delete_usuarioscomcamposadicionais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('use', 'use'), ('atual', 'atual'), ('exc', 'exc'), ('foto', 'foto'), ('menor', 'menor'))},
        ),
    ]
