# Generated by Django 4.0.8 on 2023-05-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0019_alter_tabela_notis_curriculo'),
        ('accounts', '0078_curriculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curriculo',
        ),
    ]
