# Generated by Django 4.0.8 on 2023-06-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
    ]
