# Generated by Django 4.0.8 on 2023-06-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_menores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('use', 'use'), ('atual', 'atual'), ('exc', 'exc'), ('foto', 'foto'), ('menor', 'menor'), ('responsavelMenor', 'responsavelMenor'))},
        ),
    ]
