# Generated by Django 4.0.8 on 2023-06-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dtaDeFuncaoAdm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emailAdm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='funcaoAdm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefone',
        ),
    ]
