# Generated by Django 4.0.8 on 2023-06-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_alter_instituicao_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
