# Generated by Django 4.0.8 on 2023-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_alter_instituicao_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='cnpj',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
