# Generated by Django 4.0.8 on 2023-07-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_alter_instituicao_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='banner',
        ),
    ]
