# Generated by Django 4.0.8 on 2023-07-13 01:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_remove_instituicao_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path_banner, verbose_name='Banner'),
        ),
    ]
