# Generated by Django 4.0.8 on 2023-07-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_remove_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='nomeResponsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
