# Generated by Django 4.0.8 on 2023-02-22 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0045_alter_instituicao_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('horario', models.DateTimeField(blank=True, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('qnt', models.IntegerField(blank=True, null=True)),
                ('tempo', models.IntegerField(blank=True, null=True)),
                ('idademin', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True)),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.instituicao')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
