# Generated by Django 4.0.8 on 2023-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='horario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
