# Generated by Django 4.0.8 on 2023-02-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0003_alter_voluntario_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='instituicao',
        ),
    ]
