# Generated by Django 4.0.8 on 2023-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0004_remove_voluntario_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
