# Generated by Django 4.0.8 on 2023-03-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0005_voluntario_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={'permissions': (('inst', 'inst'), ('usua', 'usua'))},
        ),
    ]
