# Generated by Django 4.0.8 on 2023-03-31 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voluntariado', '0009_voluntario_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_favo', to='voluntariado.voluntario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
