# Generated by Django 4.0.8 on 2023-03-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0010_favo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='favoC',
            field=models.IntegerField(default=0),
        ),
    ]
