# Generated by Django 4.0.8 on 2023-04-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0011_voluntario_favoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favo',
            old_name='post',
            new_name='voluntario',
        ),
    ]
