# Generated by Django 4.0.8 on 2023-04-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0012_rename_post_favo_voluntario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
