# Generated by Django 4.0.8 on 2023-04-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0013_delete_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='likes',
        ),
    ]
