# Generated by Django 4.0.8 on 2023-04-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voluntariado', '0015_rename_likes_count_voluntario_aceitar_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntariado.voluntario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
