# Generated by Django 4.0.8 on 2023-04-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0016_informar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informar',
            old_name='aceite',
            new_name='voluntario',
        ),
    ]
