# Generated by Django 4.0.8 on 2023-05-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0017_rename_aceite_informar_voluntario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voluntario',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='voluntario',
            old_name='idademin',
            new_name='idademinima',
        ),
        migrations.RenameField(
            model_name='voluntario',
            old_name='qnt',
            new_name='quantidadepessoas',
        ),
    ]
