# Generated by Django 4.0.8 on 2023-05-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0018_rename_date_voluntario_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
