# Generated by Django 4.0.8 on 2023-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0021_alter_voluntario_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
