# Generated by Django 4.0.8 on 2023-05-05 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voluntariado', '0022_alter_voluntario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_infor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informar',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_infor', to='voluntariado.voluntario'),
        ),
    ]
