# Generated by Django 4.0.8 on 2023-05-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0024_curriculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informar',
            name='voluntario',
        ),
        migrations.AddField(
            model_name='informar',
            name='curriculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_infor', to='voluntariado.curriculo'),
        ),
    ]
