# Generated by Django 4.0.8 on 2023-05-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0025_remove_informar_voluntario_informar_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='aceitar_count',
            field=models.IntegerField(default=0),
        ),
    ]
