# Generated by Django 4.0.8 on 2023-06-01 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voluntariado', '0026_curriculo_aceitar_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curiculoSender', to=settings.AUTH_USER_MODEL),
        ),
    ]
