# Generated by Django 4.0.8 on 2023-06-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0027_curriculo_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='sender',
        ),
    ]
