# Generated by Django 4.0.8 on 2023-07-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0033_alter_curriculo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='bairro',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='cidade',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='estado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='experiencia',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='rua',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
