# Generated by Django 4.0.8 on 2023-03-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='noti',
            field=models.IntegerField(blank=True, choices=[(1, 'Likes'), (2, 'Volu')], null=True),
        ),
    ]
