# Generated by Django 4.0.8 on 2023-03-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0003_rename_voluntariado_notifications_voluntario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='noti',
            field=models.IntegerField(blank=True, choices=[(1, 'Like'), (2, 'Volu')], null=True),
        ),
    ]
