# Generated by Django 4.0.8 on 2023-04-07 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0014_remove_voluntario_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0004_alter_notifications_noti'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
