# Generated by Django 4.0.8 on 2023-04-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0005_rename_notifications_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti',
            field=models.IntegerField(blank=True, choices=[(1, 'Like'), (2, 'Volu'), (3, 'Avisa')], null=True),
        ),
    ]
