# Generated by Django 4.0.8 on 2023-04-16 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0007_alter_notification_noti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_seen',
        ),
        migrations.CreateModel(
            name='TabelaNoti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipoNoti', models.IntegerField(blank=True, choices=[(1, 'Avisa')], null=True)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parauser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
