# Generated by Django 4.0.8 on 2023-04-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_aceite'),
        ('noti', '0008_remove_notification_is_seen_tabelanoti'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelanoti',
            name='tabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_tabela', to='instituicao.tabela'),
        ),
    ]
