# Generated by Django 4.0.8 on 2023-04-16 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0009_tabelanoti_tabela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabelanoti',
            old_name='remetente',
            new_name='sender',
        ),
    ]
