# Generated by Django 4.0.8 on 2023-04-16 23:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0003_rename_table_aceite_tabela'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0010_rename_remetente_tabelanoti_sender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TabelaNoti',
            new_name='Tabela_notis',
        ),
    ]
