# Generated by Django 4.0.8 on 2023-05-04 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voluntariado', '0019_delete_blogpost'),
        ('instituicao', '0008_rename_meu_tabela_user'),
        ('noti', '0011_rename_tabelanoti_tabela_notis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notificacao',
        ),
    ]
