# Generated by Django 4.0.8 on 2023-05-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0012_rename_notification_notificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='date',
            new_name='data',
        ),
    ]
