# Generated by Django 4.0.8 on 2023-05-05 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0013_rename_date_notificacao_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aceitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_infor', to=settings.AUTH_USER_MODEL)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_infor', to='noti.notificacao')),
            ],
        ),
    ]
