# Generated by Django 4.0.8 on 2023-05-21 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0016_remove_tabela_notis_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela_notis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('noti', models.IntegerField(blank=True, choices=[(1, 'Like'), (2, 'Volu')], null=True)),
                ('sender', models.ManyToManyField(related_name='enviar', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
