# Generated by Django 4.0.8 on 2023-05-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_curriculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noti', '0017_tabela_notis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_notis',
            name='curriculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notiCurriculo', to='accounts.curriculo'),
        ),
        migrations.RemoveField(
            model_name='tabela_notis',
            name='sender',
        ),
        migrations.AddField(
            model_name='tabela_notis',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envioCurriculo', to=settings.AUTH_USER_MODEL),
        ),
    ]
