# Generated by Django 4.0.8 on 2023-06-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0019_alter_tabela_notis_curriculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela_notis',
            old_name='noti',
            new_name='tabe',
        ),
    ]
