# Generated by Django 4.0.8 on 2023-06-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0020_rename_noti_tabela_notis_tabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
