# Generated by Django 4.0.8 on 2023-06-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0021_notificacao_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_notis',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tabela_notis',
            name='desempenho',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tabela_notis',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
