# Generated by Django 4.0.8 on 2023-06-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0022_tabela_notis_cargo_tabela_notis_desempenho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_notis',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
