# Generated by Django 4.0.8 on 2023-01-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('idade', models.DateTimeField(blank=True, null=True)),
                ('formacao', models.CharField(blank=True, max_length=100, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True)),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
