# Generated by Django 4.0.8 on 2023-01-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='formacao',
        ),
    ]
