# Generated by Django 4.0.8 on 2023-01-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0003_responsavel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='user',
        ),
    ]
