# Generated by Django 4.0.8 on 2023-04-16 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0009_rename_author_responsavel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='user',
        ),
    ]
