# Generated by Django 4.0.8 on 2023-05-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0011_responsavel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
