# Generated by Django 4.0.8 on 2023-06-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0013_alter_responsavel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
