# Generated by Django 4.0.8 on 2023-07-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0015_alter_responsavel_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M',
        ),
    ]
