# Generated by Django 4.0.8 on 2023-05-23 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoacaoCampanhaObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('categoria', models.CharField(choices=[['1', 'material de limpeza'], ['2', 'roupa'], ['3', 'brinquedo'], ['4', 'outros']], max_length=1, null=True)),
                ('outro', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('finalidade', models.TextField(blank=True, max_length=500, null=True)),
                ('cidade', models.CharField(max_length=150, null=True)),
                ('estado', models.CharField(max_length=150, null=True)),
                ('rua', models.CharField(max_length=150, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('bairro', models.CharField(max_length=150, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
