# Generated by Django 4.0.8 on 2023-05-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacaocampanhaobj',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
