# Generated by Django 4.0.8 on 2023-05-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0003_alter_doacaocampanhaobj_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacaocampanhaobj',
            options={'permissions': (('doacao', 'doacao'),)},
        ),
    ]
