# Generated by Django 4.0.8 on 2023-05-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0005_doacaocampanhadinheiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacaocampanhaobj',
            name='dataEntrega',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doacaocampanhaobj',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
