# Generated by Django 4.0.8 on 2023-05-28 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacao', '0007_alter_doacaocampanhaobj_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacaocampanhaobj',
            options={'permissions': (('user', 'user'),)},
        ),
        migrations.CreateModel(
            name='DoeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('dataEntrega', models.CharField(max_length=150, null=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('doacao', models.ManyToManyField(to='doacao.doacaocampanhaobj')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('user', 'user'),),
            },
        ),
    ]
