# Generated by Django 4.0.8 on 2023-05-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0008_alter_doacaocampanhaobj_options_doeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doeuser',
            name='doacao',
            field=models.ManyToManyField(null=True, to='doacao.doacaocampanhaobj'),
        ),
    ]
