# Generated by Django 4.0.8 on 2023-05-28 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0009_alter_doeuser_doacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doeuser',
            name='doacao',
        ),
        migrations.AddField(
            model_name='doeuser',
            name='doacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doacao.doacaocampanhaobj'),
        ),
    ]
