# Generated by Django 4.0.8 on 2023-05-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0010_remove_doeuser_doacao_doeuser_doacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacaocampanhaobj',
            name='dataEntrega',
        ),
        migrations.RemoveField(
            model_name='doacaocampanhaobj',
            name='quantidade',
        ),
    ]
