# Generated by Django 4.0.8 on 2023-05-28 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacao', '0011_remove_doacaocampanhaobj_dataentrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doeuser',
            name='doe',
            field=models.IntegerField(blank=True, choices=[(1, 'Doacao')], null=True),
        ),
        migrations.AddField(
            model_name='doeuser',
            name='sender',
            field=models.ManyToManyField(related_name='DoarUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
