# Generated by Django 4.0.8 on 2023-05-28 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacao', '0012_doeuser_doe_doeuser_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacaocampanhaobj',
            name='cont',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TabelarDoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabelaDoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doe_indorma', to='doacao.doacaocampanhaobj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_doar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
