# Generated by Django 4.0.8 on 2023-05-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0013_doacaocampanhaobj_cont_tabelardoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelardoe',
            name='tabelaDoe',
        ),
        migrations.AddField(
            model_name='tabelardoe',
            name='tabelaDoe',
            field=models.ManyToManyField(related_name='doe_indorma', to='doacao.doacaocampanhaobj'),
        ),
    ]
