# Generated by Django 4.0.8 on 2023-05-28 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacao', '0014_remove_tabelardoe_tabeladoe_tabelardoe_tabeladoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doeuser',
            name='sender',
        ),
        migrations.AddField(
            model_name='doeuser',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DoarUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tabelardoe',
            name='tabelaDoe',
        ),
        migrations.AddField(
            model_name='tabelardoe',
            name='tabelaDoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doe_indorma', to='doacao.doacaocampanhaobj'),
        ),
    ]
