# Generated by Django 4.0.8 on 2023-05-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0016_rename_tabeladoe_tabelardoe_doacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doeuser',
            name='dataEntrega',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doeuser',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
