# Generated by Django 4.0.8 on 2023-06-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0017_alter_doeuser_dataentrega_alter_doeuser_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaocampanhaobj',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
