# Generated by Django 4.0.8 on 2023-06-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0018_alter_doacaocampanhaobj_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaocampanhadinheiro',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
