# Generated by Django 4.0.8 on 2023-07-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0019_alter_doacaocampanhadinheiro_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaocampanhaobj',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
