# Generated by Django 4.0.8 on 2023-07-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0020_alter_doacaocampanhaobj_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaocampanhaobj',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
