# Generated by Django 4.0.8 on 2023-07-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0021_alter_doacaocampanhaobj_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaocampanhadinheiro',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
